[package]
name = "tapo-py"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "tapo"
crate-type = ["cdylib"]
doc = false

[dependencies]
chrono = { workspace = true, default-features = false }
pyo3 = { workspace = true, features = ["chrono"] }
pyo3-asyncio = { workspace = true, features = ["attributes", "tokio-runtime"] }
tapo = { path = "../tapo", features = ["python"] }
tokio = { workspace = true, default-features = false, features = ["sync"] }
